const ACTION_PREFIX = 'AUTH';

export const LOGIN_START = `${ACTION_PREFIX}/LOGIN_START`;
export const LOGIN_END = `${ACTION_PREFIX}/LOGIN_END`;
export const LOGIN_INIT = `${ACTION_PREFIX}/LOGIN_INIT`;
export const LOGIN_SUCCESS = `${ACTION_PREFIX}/LOGIN_SUCCESS`;
export const LOGIN_FAILED = `${ACTION_PREFIX}/LOGIN_FAILED`;
export const LOGOUT = `${ACTION_PREFIX}/LOGOUT`;
