const ACTION_PREFIX = 'FEED';

export const LOADING_START = `${ACTION_PREFIX}/LOADING_START`;
export const LOADING_END = `${ACTION_PREFIX}/LOADING_END`;
export const LOADING_SUCCESS = `${ACTION_PREFIX}/LOADING_SUCCESS`;
export const LOADING_FAILED = `${ACTION_PREFIX}/LOADING_FAILED`;
export const NEXT_PAGE = `${ACTION_PREFIX}/NEXT_PAGE`;
